AUGMENTATION: TRUE 
IMAGE_SIZE: [224,224,3] # as per VGG 16 model 
BATCH_SIZE: 16
INCLUDE_TOP: False      # remove FC layer 
EPOCHS: 15
CLASSES: 2
WEIGHTS: imagenet       # pretrained model 
LEARNING_RATE: 0.01 